### ISSUE TITLE
MimicJointPlugin for prismatic joints

### ISSUE THREAD

**Issue by matteolucchi** [roboticsgroup/roboticsgroup_gazebo_plugins#15]
Hi, I couldn't manage to use the MimicJointPlugin for a prismatic joint. I looked into the code and as far as I can understand, this is currently implemented only for revolute joints. I am trying to expand the functionality to prismatic joints and if I have success I'll submit a pull request. I couldn't figure out yet how to get and set positions for a prismatic joint, so if you have any advice it would be great!

Thanks for this great plugin!

**Comment by nlamprian** [comment]
Hi, the plugin actually has no logic specific to revolute joints. It can also work with prismatic with no problems. At a basic level, all you have to specify are the active and mimic joint names. The plugin itself is not touching any limits. You should focus on your URDF. If, for example, the joint limits are same and you have a -1 multiplier for the mimic joint, you should reverse the limits for the mimic joint. Otherwise, gazebo wouldn't be able to move it.

**Comment by matteolucchi** [comment]
You are completely right, there was an error in my urdf model! Sorry for the noise, and thanks again for the great plugin ;)
